'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

 '''<summary>
 '''plTnWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTnWidth As UserControl

 '''<summary>
 '''txtTnWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTnWidth As TextBox

 '''<summary>
 '''Comparevalidator1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator1 As CompareValidator

 '''<summary>
 '''Requiredfieldvalidator1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator1 As RequiredFieldValidator

 '''<summary>
 '''plTnHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTnHeight As UserControl

 '''<summary>
 '''txtTnHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTnHeight As TextBox

 '''<summary>
 '''Comparevalidator2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator2 As CompareValidator

 '''<summary>
 '''Requiredfieldvalidator2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator2 As RequiredFieldValidator

 '''<summary>
 '''plTnFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTnFit As UserControl

 '''<summary>
 '''ddTnFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddTnFit As DropDownList

 '''<summary>
 '''plMedWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plMedWidth As UserControl

 '''<summary>
 '''txtMedWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtMedWidth As TextBox

 '''<summary>
 '''Comparevalidator3 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator3 As CompareValidator

 '''<summary>
 '''Requiredfieldvalidator3 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator3 As RequiredFieldValidator

 '''<summary>
 '''plMedHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plMedHeight As UserControl

 '''<summary>
 '''txtMedHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtMedHeight As TextBox

 '''<summary>
 '''Comparevalidator4 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator4 As CompareValidator

 '''<summary>
 '''Requiredfieldvalidator4 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator4 As RequiredFieldValidator

 '''<summary>
 '''plMedFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plMedFit As UserControl

 '''<summary>
 '''ddMedFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddMedFit As DropDownList

 '''<summary>
 '''plZoomWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomWidth As UserControl

 '''<summary>
 '''txtZoomWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtZoomWidth As TextBox

 '''<summary>
 '''Comparevalidator5 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator5 As CompareValidator

 '''<summary>
 '''Requiredfieldvalidator5 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator5 As RequiredFieldValidator

 '''<summary>
 '''plZoomHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomHeight As UserControl

 '''<summary>
 '''txtZoomHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtZoomHeight As TextBox

 '''<summary>
 '''Comparevalidator6 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator6 As CompareValidator

 '''<summary>
 '''Requiredfieldvalidator6 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator6 As RequiredFieldValidator

 '''<summary>
 '''plZoomFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomFit As UserControl

 '''<summary>
 '''ddZoomFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddZoomFit As DropDownList
End Class
