'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

 '''<summary>
 '''plTnWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTnWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTnWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTnWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator1 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plTnHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTnHeight As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTnHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTnHeight As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator2 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plTnFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plTnFit As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddTnFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddTnFit As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plMedWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plMedWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtMedWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtMedWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator3 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator3 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator3 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plMedHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plMedHeight As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtMedHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtMedHeight As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator4 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator4 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator4 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plMedFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plMedFit As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddMedFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddMedFit As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''plZoomWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtZoomWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtZoomWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator5 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator5 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator5 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plZoomHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomHeight As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtZoomHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtZoomHeight As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Comparevalidator6 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Comparevalidator6 As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''Requiredfieldvalidator6 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Requiredfieldvalidator6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plZoomFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plZoomFit As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddZoomFit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddZoomFit As Global.System.Web.UI.WebControls.DropDownList
End Class
